<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '9.0.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'Exp',
  'author' => 'Bhea',
  'description' => 'This package contains only Expenses module.',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Expenses',
  'published_date' => '2019-05-25 08:23:53',
  'type' => 'module',
  'version' => 1558772633,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Expenses',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'Exp_Expenses',
      'class' => 'Exp_Expenses',
      'path' => 'modules/Exp_Expenses/Exp_Expenses.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/exp_expenses_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/exp_expenses_meetingsMetaData.php',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Exp_Expenses',
      'to' => 'modules/Exp_Expenses',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'bg_BG',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'cs_CZ',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'da_DK',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'de_DE',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'el_EL',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'es_ES',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'fr_FR',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'he_IL',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'hu_HU',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'hr_HR',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'it_it',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'lt_LT',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'ja_JP',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'ko_KR',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'lv_LV',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'nb_NO',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'nl_NL',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'pl_PL',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'pt_PT',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'ro_RO',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'ru_RU',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'sv_SE',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'th_TH',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'tr_TR',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'zh_TW',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'zh_CN',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'pt_BR',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'ca_ES',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_UK',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'sr_RS',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'sk_SK',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'sq_AL',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'et_EE',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'es_LA',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'fi_FI',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'ar_SA',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'uk_UA',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'en_us',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'bg_BG',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'cs_CZ',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'da_DK',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'de_DE',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'el_EL',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'es_ES',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'fr_FR',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'he_IL',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'hu_HU',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'hr_HR',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'it_it',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'lt_LT',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'ja_JP',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'ko_KR',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'lv_LV',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'nb_NO',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'nl_NL',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'pl_PL',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'pt_PT',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'ro_RO',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'ru_RU',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'sv_SE',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'th_TH',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'tr_TR',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'zh_TW',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'zh_CN',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'pt_BR',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'ca_ES',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'en_UK',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'sr_RS',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'sk_SK',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'sq_AL',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'et_EE',
    ),
    72 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'es_LA',
    ),
    73 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'fi_FI',
    ),
    74 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'ar_SA',
    ),
    75 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
      'language' => 'uk_UA',
    ),
    76 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ar_SA.lang.php',
      'to_module' => 'application',
      'language' => 'ar_SA',
    ),
    77 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/th_TH.lang.php',
      'to_module' => 'application',
      'language' => 'th_TH',
    ),
    78 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/nb_NO.lang.php',
      'to_module' => 'application',
      'language' => 'nb_NO',
    ),
    79 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_UK.lang.php',
      'to_module' => 'application',
      'language' => 'en_UK',
    ),
    80 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/hr_HR.lang.php',
      'to_module' => 'application',
      'language' => 'hr_HR',
    ),
    81 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/fr_FR.lang.php',
      'to_module' => 'application',
      'language' => 'fr_FR',
    ),
    82 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/fi_FI.lang.php',
      'to_module' => 'application',
      'language' => 'fi_FI',
    ),
    83 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/tr_TR.lang.php',
      'to_module' => 'application',
      'language' => 'tr_TR',
    ),
    84 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ca_ES.lang.php',
      'to_module' => 'application',
      'language' => 'ca_ES',
    ),
    85 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/zh_CN.lang.php',
      'to_module' => 'application',
      'language' => 'zh_CN',
    ),
    86 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/sq_AL.lang.php',
      'to_module' => 'application',
      'language' => 'sq_AL',
    ),
    87 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/it_it.lang.php',
      'to_module' => 'application',
      'language' => 'it_it',
    ),
    88 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/pt_BR.lang.php',
      'to_module' => 'application',
      'language' => 'pt_BR',
    ),
    89 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/pt_PT.lang.php',
      'to_module' => 'application',
      'language' => 'pt_PT',
    ),
    90 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/et_EE.lang.php',
      'to_module' => 'application',
      'language' => 'et_EE',
    ),
    91 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ro_RO.lang.php',
      'to_module' => 'application',
      'language' => 'ro_RO',
    ),
    92 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/el_EL.lang.php',
      'to_module' => 'application',
      'language' => 'el_EL',
    ),
    93 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ko_KR.lang.php',
      'to_module' => 'application',
      'language' => 'ko_KR',
    ),
    94 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ru_RU.lang.php',
      'to_module' => 'application',
      'language' => 'ru_RU',
    ),
    95 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/sv_SE.lang.php',
      'to_module' => 'application',
      'language' => 'sv_SE',
    ),
    96 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/zh_TW.lang.php',
      'to_module' => 'application',
      'language' => 'zh_TW',
    ),
    97 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/sk_SK.lang.php',
      'to_module' => 'application',
      'language' => 'sk_SK',
    ),
    98 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    99 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ja_JP.lang.php',
      'to_module' => 'application',
      'language' => 'ja_JP',
    ),
    100 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/bg_BG.lang.php',
      'to_module' => 'application',
      'language' => 'bg_BG',
    ),
    101 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/uk_UA.lang.php',
      'to_module' => 'application',
      'language' => 'uk_UA',
    ),
    102 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/da_DK.lang.php',
      'to_module' => 'application',
      'language' => 'da_DK',
    ),
    103 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    104 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/nl_NL.lang.php',
      'to_module' => 'application',
      'language' => 'nl_NL',
    ),
    105 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/pl_PL.lang.php',
      'to_module' => 'application',
      'language' => 'pl_PL',
    ),
    106 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_LA.lang.php',
      'to_module' => 'application',
      'language' => 'es_LA',
    ),
    107 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/sr_RS.lang.php',
      'to_module' => 'application',
      'language' => 'sr_RS',
    ),
    108 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/de_DE.lang.php',
      'to_module' => 'application',
      'language' => 'de_DE',
    ),
    109 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/hu_HU.lang.php',
      'to_module' => 'application',
      'language' => 'hu_HU',
    ),
    110 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/he_IL.lang.php',
      'to_module' => 'application',
      'language' => 'he_IL',
    ),
    111 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/lv_LV.lang.php',
      'to_module' => 'application',
      'language' => 'lv_LV',
    ),
    112 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/lt_LT.lang.php',
      'to_module' => 'application',
      'language' => 'lt_LT',
    ),
    113 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/cs_CZ.lang.php',
      'to_module' => 'application',
      'language' => 'cs_CZ',
    ),
  ),
  'sidecar' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/clients/base/layouts/subpanels/exp_expenses_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/clients/mobile/layouts/subpanels/exp_expenses_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/exp_expenses_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/exp_expenses_meetings_Exp_Expenses.php',
      'to_module' => 'Exp_Expenses',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
  'wireless_subpanels' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/exp_expenses_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
  ),
  'image_dir' => '<basepath>/icons',
);